#
# This configuration file is intended to provide a standalone local network
# with a single validator.
#
# This configuration is provided for the convenience of developers and should
# not be used in production. See `doc/config.example.yaml` for a full,
# up to date example of the configuration options available
#
# Run from the root with:
# ./build/agora -c devel/config-single.yaml

node:
  realm: "localhost"
  testing: true
  limit_test_validators: 1
  data_dir: .cache
  # Can be used with curl or just a browser
  stats_listening_port: 9111

interfaces:
  - type:    http
    address: 0.0.0.0
    port:    2826

consensus:
  block_interval:
    seconds: 30
  validator_cycle: 20
  genesis_timestamp: 1644980571

validator:
  enabled: true
  # We use first of Genesis Block enrollments: val5: boa1xrval5rzmma29zh4aqgv3mvcarhwa0w8rgthy3l9vaj3fywf9894ycmjkm8
  seed: SAZO4WA5SXUN3J6XBXZCFPXJJZ62IQAJYAG2KBVWF2QZKTU2WK3QTNMV
  registry_address: http://agora:2826/
  addresses_to_register:
    - http://agora:2826/

registry:
  enabled: true
  address: 127.0.0.1
  # Use a non-priviledged port to avoid a clash with the system resolver
  port: 5335
  validators:
    authoritative: true
    primary: localhost
    soa:
      email: no@no.no
  flash:
    authoritative: true
    primary: localhost
    soa:
      email: no@no.no

admin:
  enabled: true
  tls: false
  address: 0.0.0.0
  port:    2827
  username: admin
  pwd: s3cr3t

# The node will self-ban but this section needs at least one entry
network:
  - https://agora:2826/

logging:
  root:
    level: Info
    console: true
  # agora:
  #   level: Trace
  #   console: false
  #   file: .single/log/agora.log

event_handlers:
  # URLs to push a data when a block is externalized. (path is "/block_externalized")
  BlockExternalized:
    addresses:
      - http://stoa:3837/block_externalized
  # URLs to push a data when a block header is updated. (path is "/block_header_updated")
  BlockHeaderUpdated:
    addresses:
      - http://stoa:3837/block_header_updated
  # URLs to push a data when a pre-image is updated. (path is "/preimage_received")
  PreimageReceived:
    addresses:
      - http://stoa:3837/preimage_received
  # URLs to push a data when a transaction is updated. (path is "/transaction_received")
  TransactionReceived:
    addresses:
      - http://stoa:3837/transaction_received
